# Generated by Django 4.1.5 on 2023-01-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(upload_to='media')),
                ('user_qr_code', models.ImageField(blank=True, null=True, upload_to='user_qrcode')),
                ('cnic', models.CharField(max_length=13, unique=True)),
                ('Licence_number', models.CharField(max_length=20)),
                ('Driver_name', models.CharField(max_length=120)),
                ('Father_name', models.CharField(max_length=120)),
                ('Allowed_Vehcial', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=120)),
                ('issue_date', models.DateField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
            ],
        ),
    ]
