# Generated by Django 4.1.5 on 2023-01-13 11:55

import Dlimsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dlimsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user_qr_code',
        ),
        migrations.AlterField(
            model_name='client',
            name='pic',
            field=models.ImageField(upload_to='media', validators=[Dlimsapp.models.Client.validate_image]),
        ),
    ]
